### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by CrazyPython** [rshk/elo#1]
Right now we can't legally use this in our own projects.

**Comment by rshk** [comment]
Oh, I just assumed people were going to copy paste the content of those functions, it's not actually a big library.. consider it BSD though, I can add a license file if you actually need to use this as a library

**Comment by CrazyPython** [comment]
Since it's such a small license, you might be willing to put it in the public domain: just put a CC0 license  in the root directory.

**Comment by CrazyPython** [comment]
(I did copy-paste those functions btw)

**Comment by choigawoon** [comment]
I gonna make a simple match maker using Elo Rating System, and I'd like to use yours as Elo Rater.
If there is a problem, let me know. Thanks!

**Comment by rshk** [comment]
Added public domain license in #2 (I'm not even sure I would have any rights to license that code btw -- anyone heading to https://en.wikipedia.org/wiki/Elo_rating_system and copying down the formulas would end up with basically the same thing..)
